spring:
  application:
    name: tools

server:
  port: 8805

langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.mnzdna.xyz/v1
      api-key: sk-KgvugzpKzki15GFxB72e7782De844b23B3E4Fc6dDf40B29a
