server:
  port: 8801
spring:
  application:
    name: chat-service
langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: qwen:7b
  open-ai:
    chat-model:
      api-key: xxxxxx
      base-url: xxxxxx